### ISSUE TITLE
Unable to run local test because of invalid "SDK_CALLBACK_URL"

### ISSUE THREAD

**Issue by JamesJeffryes** [kbase/kb_sdk#256]
I'm developing a package with the kb_sdk but have run into a roadblock in running the local tests. It seems that the value of the SDK_CALLBACK_URL does not get set resulting in the error below when my application attempts to create a kbase report. 

The code for this module in progress is located [in this repo](https://github.com/JamesJeffryes/MetabolomicsTools) but I have encountered a similar error executing local tests on another module (which works locally for @janakagithub). Additionally I've tried a fresh install and build of the sdk on my local machine and an install and build on another OSX laptop and encountered the same error.

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
Run Tests
if [ ! -f /kb/module/work/token ]; then echo -e '\nOutside a docker container please run "kb-sdk test" rather than "make test"\n' && exit 1; fi
bash test/run_tests.sh
E
======================================================================
ERROR: test_get_spectra (MetabolomicsTools_server_test.MetabolomicsToolsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/kb/module/test/MetabolomicsTools_server_test.py", line 85, in test_get_spectra
    result = self.getImpl().get_spectra(self.getContext(), params)
  File "/kb/module/lib/MetabolomicsTools/MetabolomicsToolsImpl.py", line 132, in get_spectra
    report_info = report_client.create_extended_report(report_params)
  File "/kb/module/lib/KBaseReport/KBaseReportClient.py", line 160, in create_extended_report
    job_id = self._create_extended_report_submit(params, context)
  File "/kb/module/lib/KBaseReport/KBaseReportClient.py", line 106, in _create_extended_report_submit
    self._service_ver, context)
  File "/kb/module/lib/KBaseReport/baseclient.py", line 223, in _submit_job
    args, context)
  File "/kb/module/lib/KBaseReport/baseclient.py", line 177, in _call
    verify=not self.trust_all_ssl_certificates)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='fakecallbackurl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b00f2c3c250>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by MrCreosote** [comment]
Hi James,

The fakecallbackurl address tells me that the test runner code couldn't figure out the proper callback server url from your environment, but I'm not an expert if that portion of the code. The best way for you to get the help you need is via submitting a ticket in our help system here: http://kbase.us/using-the-kbase-help-board/

There's no guarantee that anyone will see github issues as we don't track them at all.

Cheers!
